2019-12-21 14:21:58,251ERROR: Exception on /reset_password_request [POST] [in c:\users\hp\desktop\hp1\venv\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\hp\desktop\hp1\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\hp\desktop\hp1\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\hp\desktop\hp1\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\hp\desktop\hp1\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\hp\desktop\hp1\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\hp\desktop\hp1\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\HP\Desktop\hp1\app\routes.py", line 141, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\HP\Desktop\hp1\app\email.py", line 18, in send_password_reset_email
    text_body=render_template('email/reset_password.txt',
  File "c:\users\hp\desktop\hp1\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\hp\desktop\hp1\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\hp\desktop\hp1\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\hp\desktop\hp1\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\hp\desktop\hp1\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\hp\desktop\hp1\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\HP\Desktop\hp1\app\templates\email\reset_password.txt", line 1, in <module>
    Dear {{ user.username }},
  File "c:\users\hp\desktop\hp1\venv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'user' is undefined
2019-12-21 14:25:08,379INFO: Microblog startup [in C:\Users\HP\Desktop\hp1\app\__init__.py:47]
2019-12-21 14:26:38,626ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6NCwiZXhwIjoxNTc2OTE5MTIzLjcyMTEyNDJ9.jmZ1mi6lcTp4r6Ekr9FX-ecRCpv6xXx6FvOsbuXUNyc [GET] [in c:\users\hp\desktop\hp1\venv\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\hp\desktop\hp1\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\hp\desktop\hp1\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\hp\desktop\hp1\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\hp\desktop\hp1\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\hp\desktop\hp1\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\hp\desktop\hp1\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\HP\Desktop\hp1\app\routes.py", line 151, in reset_password
    user = User.verify_reset_password(token)
AttributeError: type object 'User' has no attribute 'verify_reset_password'
2019-12-21 14:28:35,263INFO: Microblog startup [in C:\Users\HP\Desktop\hp1\app\__init__.py:47]
2019-12-21 21:21:40,001INFO: Microblog startup [in C:\Users\HP\Desktop\hp1\app\__init__.py:47]
2019-12-21 21:35:26,234INFO: Microblog startup [in C:\Users\HP\Desktop\hp1\app\__init__.py:47]
2019-12-22 02:16:53,365INFO: Microblog startup [in C:\Users\HP\Desktop\hp1\app\__init__.py:51]
2019-12-23 01:02:38,979INFO: Microblog startup [in C:\Users\HP\Desktop\hp1\app\__init__.py:51]
2019-12-23 02:15:30,455INFO: Microblog startup [in C:\Users\HP\Desktop\hp1\app\__init__.py:51]
