2019-12-25 00:37:37,443 INFO: Microblog startup [in C:\Users\HP\Desktop\hp1\app\__init__.py:72]
2019-12-25 00:39:09,707 INFO: Microblog startup [in C:\Users\HP\Desktop\hp1\app\__init__.py:72]
2019-12-25 00:39:28,681 INFO: Microblog startup [in C:\Users\HP\Desktop\hp1\app\__init__.py:72]
2019-12-25 00:39:28,681 INFO: Microblog startup [in C:\Users\HP\Desktop\hp1\app\__init__.py:72]
2019-12-25 00:43:10,596 INFO: Microblog startup [in C:\Users\HP\Desktop\hp1\app\__init__.py:72]
2019-12-25 00:56:16,582 INFO: Microblog startup [in C:\Users\HP\Desktop\hp1\app\__init__.py:72]
2019-12-25 00:58:43,181 INFO: Microblog startup [in C:\Users\HP\Desktop\hp1\app\__init__.py:72]
2019-12-25 01:07:07,737 INFO: Microblog startup [in C:\Users\HP\Desktop\hp1\app\__init__.py:72]
2019-12-25 02:11:30,491 INFO: Microblog startup [in C:\Users\HP\Desktop\hp1\app\__init__.py:76]
2019-12-25 02:15:24,088 INFO: Microblog startup [in C:\Users\HP\Desktop\hp1\app\__init__.py:76]
2019-12-25 02:41:20,985 INFO: Microblog startup [in C:\Users\HP\Desktop\hp1\app\__init__.py:76]
2019-12-25 02:58:44,956 INFO: Microblog startup [in C:\Users\HP\Desktop\hp1\app\__init__.py:76]
2019-12-28 17:03:01,622 INFO: Microblog startup [in C:\Users\HP\Desktop\hp1\app\__init__.py:76]
2019-12-28 17:44:57,407 INFO: Microblog startup [in C:\Users\HP\Desktop\hp1\app\__init__.py:76]
2019-12-29 00:29:58,957 INFO: Microblog startup [in C:\Users\HP\Desktop\hp1\app\__init__.py:76]
2020-01-01 00:49:46,463 INFO: Microblog startup [in C:\Users\HP\Desktop\backup2\talentdisha\app\__init__.py:80]
2020-01-01 00:57:49,744 INFO: Microblog startup [in C:\Users\HP\Desktop\backup2\talentdisha\app\__init__.py:80]
2020-01-01 01:02:15,995 INFO: Microblog startup [in C:\Users\HP\Desktop\backup2\talentdisha\app\__init__.py:80]
2020-01-01 01:02:19,439 ERROR: Exception on /home [GET] [in c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\HP\Desktop\backup2\talentdisha\app\main\routes.py", line 41, in home
    return render_template('homepage.html', title='TalentDisha')
  File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\HP\Desktop\backup2\talentdisha\app\templates\homepage.html", line 94, in <module>
    <a href="{{url_for('main.login') }}">Jobseeker</a>
  File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.login'. Did you mean 'main.org' instead?
2020-01-01 01:03:59,224 INFO: Microblog startup [in C:\Users\HP\Desktop\backup2\talentdisha\app\__init__.py:80]
2020-01-04 15:07:45,093 INFO: Microblog startup [in C:\Users\HP\Desktop\talentdisha\app\__init__.py:80]
2020-01-04 15:09:07,072 INFO: Microblog startup [in C:\Users\HP\Desktop\talentdisha\app\__init__.py:80]
2020-01-04 15:12:07,529 INFO: Microblog startup [in C:\Users\HP\Desktop\talentdisha\app\__init__.py:80]
2020-01-04 15:12:15,932 ERROR: Exception on /home [GET] [in c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\HP\Desktop\talentdisha\app\main\routes.py", line 46, in home
    return render_template('homepage7.html', title='Home')
  File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\HP\Desktop\talentdisha\app\templates\homepage7.html", line 186, in <module>
    <li><a href="{{ url_for('who_we_are') }}"><span class="glyphicon glyphicon-user"></span> Who We Are</a></li>
  File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'who_we_are'. Did you mean 'main.who_we_are' instead?
2020-01-04 15:23:23,082 INFO: Microblog startup [in C:\Users\HP\Desktop\talentdisha\app\__init__.py:80]
